# Generated by Django 4.2.11 on 2025-10-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostScan',
            fields=[
                ('hostname', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ports', models.JSONField(default=list)),
                ('cnames', models.JSONField(default=list)),
                ('ptr', models.CharField(blank=True, max_length=255, null=True)),
                ('txt', models.TextField(blank=True, null=True)),
                ('subs', models.JSONField(default=list)),
                ('live_subs', models.JSONField(default=list)),
                ('waf', models.CharField(blank=True, max_length=100, null=True)),
                ('technology', models.CharField(blank=True, max_length=255, null=True)),
                ('crawled_urls', models.JSONField(default=list)),
                ('archived_urls', models.JSONField(default=list)),
                ('virustotal_urls', models.JSONField(default=list)),
                ('all_urls', models.JSONField(default=list)),
                ('parameters', models.JSONField(default=list)),
                ('endpoints', models.JSONField(default=list)),
                ('js_files', models.JSONField(default=list)),
                ('js_secrets', models.JSONField(default=list)),
                ('js_urls', models.JSONField(default=list)),
                ('js_endpoints', models.JSONField(default=list)),
                ('vuln', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
