# Generated by Django 4.2.11 on 2025-10-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=1000)),
                ('ip', models.CharField(max_length=1000)),
                ('ports', models.TextField()),
            ],
        ),
    ]
