# Generated by Django 4.2.11 on 2025-11-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomain',
            name='cname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='ip',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
