# Generated by Django 4.2.11 on 2025-10-26 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='hostname',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
