# Generated by Django 4.2.11 on 2025-11-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subdomain_cname_subdomain_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_number', models.IntegerField()),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='core.subdomain')),
            ],
            options={
                'unique_together': {('subdomain', 'port_number')},
            },
        ),
    ]
