# Generated by Django 4.2.11 on 2025-12-06 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPX',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_code', models.IntegerField()),
                ('url', models.CharField(max_length=1000000)),
                ('content_length', models.IntegerField()),
                ('tech', models.JSONField(default=list)),
                ('location', models.CharField(max_length=1000000)),
                ('title', models.CharField(max_length=1000000)),
                ('subdomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='httpxs', to='core.subdomain')),
            ],
            options={
                'unique_together': {('subdomain', 'url')},
            },
        ),
    ]
