# Generated by Django 4.2.11 on 2025-12-06 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_httpx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='httpx',
            name='content_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httpx',
            name='location',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='httpx',
            name='status_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='httpx',
            name='subdomain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='httpx', to='core.subdomain'),
        ),
        migrations.AlterField(
            model_name='httpx',
            name='tech',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='httpx',
            name='title',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='httpx',
            name='url',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
